// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace Subscriptions.Tests.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("Autentica��o do candidato")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    [global::NUnit.Framework.CategoryAttribute("chrome")]
    [global::NUnit.Framework.CategoryAttribute("edge")]
    [global::NUnit.Framework.CategoryAttribute("firefox")]
    public partial class AutenticaODoCandidatoFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "chrome",
                "edge",
                "firefox"};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("pt"), "Features", "Autentica��o do candidato", "  Como candidato\r\n  Eu quero realizar login na �rea do candidato\r\n  Para acessar " +
                "minha inscri��o\r\n\r\n  Cen�rio: Visualizar tela de autentica��o\r\n    Dado que o us" +
                "u�rio acessa a tela de login\r\n    Ent�o deve visualizar o campo \"Usu�rio\"\r\n    E" +
                " deve visualizar o campo \"Senha\"\r\n    E deve visualizar o bot�o \"Login\"\r\n    E d" +
                "eve visualizar a op��o \"Recuperar usu�rio\"\r\n    E deve visualizar a op��o \"Redef" +
                "inir senha\"\r\n    E bot�o Privacidade\r\n    E bot�o home\r\n    E op��es de tema\r\n  " +
                "  E logotipo +a\r\n    E bot�o Portal de inscri��es\r\n\r\n  Cen�rio: Tentar realizar " +
                "login com campos vazios\r\n    Dado que o usu�rio est� na tela de login\r\n    Quand" +
                "o clica no bot�o \"Login\" sem preencher os campos\r\n    Ent�o deve visualizar mens" +
                "agens de valida��o\r\n\r\n  Cen�rio: Realizar login com credenciais inv�lidas\r\n    D" +
                "ado que o usu�rio est� na tela de login\r\n    Quando informa usu�rio ou senha inv" +
                "�lidos\r\n    E clica no bot�o \"Login\"\r\n    Ent�o deve visualizar mensagem de erro" +
                " de autentica��o\r\n\r\n  Cen�rio: Realizar login com sucesso\r\n    Dado que o usu�ri" +
                "o est� na tela de login\r\n    Quando informa usu�rio e senha v�lidos\r\n    E clica" +
                " no bot�o \"Login\"\r\n    Ent�o deve acessar a �rea do candidato\r\n\r\n  Cen�rio: Aces" +
                "sar recupera��o de usu�rio\r\n    Dado que o usu�rio est� na tela de login\r\n    Qu" +
                "ando clica em \"Recuperar usu�rio\"\r\n    Ent�o deve enviado email com instru��es p" +
                "ara recupera��o\r\n\r\n  Cen�rio: Acessar redefini��o de senha\r\n    Dado que o usu�r" +
                "io est� na tela de login\r\n    Quando clica em \"Redefinir senha\"\r\n    Ent�o deve " +
                "enviado email com instru��es para recupera��o", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "autenticacao_candidato.feature"
#line hidden
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/autenticacao_candidato.feature.ndjson", 2);
        }
    }
}
#pragma warning restore
#endregion
