// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace Subscriptions.Tests.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("Preenchimento do formulário de inscrição")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    [global::NUnit.Framework.CategoryAttribute("chrome")]
    [global::NUnit.Framework.CategoryAttribute("edge")]
    [global::NUnit.Framework.CategoryAttribute("firefox")]
    public partial class PreenchimentoDoFormularioDeInscricaoFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "chrome",
                "edge",
                "firefox"};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("pt"), "Features", "Preenchimento do formulário de inscrição", "  Como candidato\r\n  Eu quero preencher meus dados pessoais e de contato\r\n  Para p" +
                "rosseguir com minha inscrição", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Formulario_inscricao.feature.ndjson", 30);
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Visualizar formulário de inscrição")]
        public async global::System.Threading.Tasks.Task VisualizarFormularioDeInscricao()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Visualizar formulário de inscrição", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
            this.ScenarioInitialize(scenarioInfo, ruleInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                await testRunner.GivenAsync("que o usuário avançou após selecionar um curso", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
                await testRunner.ThenAsync("deve visualizar a seção \"Dados pessoais\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
                await testRunner.AndAsync("deve visualizar os campos CPF, Nome, Sobrenome e Data de nascimento", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
                await testRunner.AndAsync("deve visualizar a seção \"Contato\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
                await testRunner.AndAsync("deve visualizar os campos Email, Celular e Telefone", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
                await testRunner.AndAsync("deve visualizar a seção \"Endereço\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
                await testRunner.AndAsync("deve visualizar campos de endereço", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
                await testRunner.AndAsync("deve visualizar o botão \"Voltar\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
                await testRunner.AndAsync("deve visualizar o botão \"Avançar\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
                await testRunner.AndAsync("deve visualizar botão Privacidade", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
                await testRunner.AndAsync("deve visualizar botão home", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
                await testRunner.AndAsync("deve visualizar opções de tema", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
                await testRunner.AndAsync("deve visualizar logotipo +a", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
                await testRunner.AndAsync("deve visualizar botão Portal de inscrições", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Tentar avançar com formulário vazio")]
        public async global::System.Threading.Tasks.Task TentarAvancarComFormularioVazio()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Tentar avançar com formulário vazio", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
            this.ScenarioInitialize(scenarioInfo, ruleInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                await testRunner.GivenAsync("que o usuário está no formulário de inscrição", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
                await testRunner.WhenAsync("clica em \"Avançar\" sem preencher os campos obrigatórios", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
                await testRunner.ThenAsync("deve visualizar mensagens de validação nos campos obrigatórios", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Preencher formulário com dados válidos")]
        public async global::System.Threading.Tasks.Task PreencherFormularioComDadosValidos()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Preencher formulário com dados válidos", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
            this.ScenarioInitialize(scenarioInfo, ruleInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                await testRunner.GivenAsync("que o usuário está no formulário de inscrição", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
                await testRunner.WhenAsync("preenche todos os campos obrigatórios corretamente", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
                await testRunner.AndAsync("clica em \"Avançar\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
                await testRunner.ThenAsync("deve avançar para a próxima etapa da inscrição", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Preencher CPF em formato inválido")]
        public async global::System.Threading.Tasks.Task PreencherCPFEmFormatoInvalido()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Preencher CPF em formato inválido", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
            this.ScenarioInitialize(scenarioInfo, ruleInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                await testRunner.GivenAsync("que o usuário está no formulário de inscrição", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
                await testRunner.WhenAsync("informa um CPF em formato inválido", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
                await testRunner.ThenAsync("deve visualizar mensagem de erro no campo CPF", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Preencher email inválido")]
        public async global::System.Threading.Tasks.Task PreencherEmailInvalido()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Preencher email inválido", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
            this.ScenarioInitialize(scenarioInfo, ruleInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                await testRunner.GivenAsync("que o usuário está no formulário de inscrição", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
                await testRunner.WhenAsync("informa um email em formato inválido", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
                await testRunner.ThenAsync("deve visualizar mensagem de erro no campo Email", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Preencher telefone em formato inválido")]
        public async global::System.Threading.Tasks.Task PreencherTelefoneEmFormatoInvalido()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Preencher telefone em formato inválido", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
            this.ScenarioInitialize(scenarioInfo, ruleInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                await testRunner.GivenAsync("que o usuário está no formulário de inscrição", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
                await testRunner.WhenAsync("informa um telefone em formato inválido", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
                await testRunner.ThenAsync("deve visualizar mensagem de erro no campo Telefone", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Preencher data de nascimento inválida")]
        public async global::System.Threading.Tasks.Task PreencherDataDeNascimentoInvalida()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "6";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Preencher data de nascimento inválida", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
            this.ScenarioInitialize(scenarioInfo, ruleInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                await testRunner.GivenAsync("que o usuário está no formulário de inscrição", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
                await testRunner.WhenAsync("informa uma data de nascimento inválida", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
                await testRunner.ThenAsync("deve visualizar mensagem de erro no campo Data de nascimento", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Preencher CEP em formato inválido")]
        public async global::System.Threading.Tasks.Task PreencherCEPEmFormatoInvalido()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "7";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Preencher CEP em formato inválido", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
            this.ScenarioInitialize(scenarioInfo, ruleInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                await testRunner.GivenAsync("que o usuário está no formulário de inscrição", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
                await testRunner.WhenAsync("informa um CEP em formato inválido", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
                await testRunner.ThenAsync("deve visualizar mensagem de erro no campo CEP", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Marcar opção possui deficiência")]
        public async global::System.Threading.Tasks.Task MarcarOpcaoPossuiDeficiencia()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "8";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Marcar opção possui deficiência", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
            this.ScenarioInitialize(scenarioInfo, ruleInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                await testRunner.GivenAsync("que o usuário está no formulário de inscrição", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
                await testRunner.WhenAsync("marca a opção \"Possui alguma deficiência?\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
                await testRunner.ThenAsync("o sistema deve registrar a escolha do usuário", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Navegar para tela anterior")]
        public async global::System.Threading.Tasks.Task NavegarParaTelaAnterior()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "9";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Navegar para tela anterior", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
            this.ScenarioInitialize(scenarioInfo, ruleInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                await testRunner.GivenAsync("que o usuário está no formulário de inscrição", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
                await testRunner.WhenAsync("clica no botão \"Voltar\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
                await testRunner.ThenAsync("deve retornar para a tela anterior da inscrição", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Preencher parcialmente o formulário")]
        public async global::System.Threading.Tasks.Task PreencherParcialmenteOFormulario()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "10";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Preencher parcialmente o formulário", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
            this.ScenarioInitialize(scenarioInfo, ruleInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                await testRunner.GivenAsync("que o usuário está no formulário de inscrição", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
                await testRunner.WhenAsync("preenche apenas alguns campos obrigatórios", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
                await testRunner.AndAsync("tenta avançar", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
                await testRunner.ThenAsync("deve visualizar quais campos obrigatórios não foram preenchidos", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Inserir caracteres especiais em campos de texto")]
        public async global::System.Threading.Tasks.Task InserirCaracteresEspeciaisEmCamposDeTexto()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "11";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Inserir caracteres especiais em campos de texto", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
            this.ScenarioInitialize(scenarioInfo, ruleInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                await testRunner.GivenAsync("que o usuário está no formulário de inscrição", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
                await testRunner.WhenAsync("insere caracteres inválidos em campos de texto", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
                await testRunner.ThenAsync("deve visualizar mensagem de validação", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Informar CPF com mais de 12 caracteres")]
        public async global::System.Threading.Tasks.Task InformarCPFComMaisDe12Caracteres()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "12";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Informar CPF com mais de 12 caracteres", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
            this.ScenarioInitialize(scenarioInfo, ruleInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                await testRunner.GivenAsync("que o usuário está no formulário de inscrição", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
                await testRunner.WhenAsync("informa um CPF com mais de 12 caracteres", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
                await testRunner.ThenAsync("o sistema deve impedir a digitação adicional ou exibir validação de limite máximo" +
                        "", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Informar CPF com quantidade máxima permitida")]
        public async global::System.Threading.Tasks.Task InformarCPFComQuantidadeMaximaPermitida()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "13";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Informar CPF com quantidade máxima permitida", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
            this.ScenarioInitialize(scenarioInfo, ruleInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                await testRunner.GivenAsync("que o usuário está no formulário de inscrição", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
                await testRunner.WhenAsync("informa um CPF com até 12 caracteres", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
                await testRunner.ThenAsync("o sistema deve aceitar o valor informado", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Informar telefone com menos de 10 caracteres")]
        public async global::System.Threading.Tasks.Task InformarTelefoneComMenosDe10Caracteres()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "14";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Informar telefone com menos de 10 caracteres", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
            this.ScenarioInitialize(scenarioInfo, ruleInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                await testRunner.GivenAsync("que o usuário está no formulário de inscrição", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
                await testRunner.WhenAsync("informa um telefone com menos de 10 caracteres", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
                await testRunner.AndAsync("tenta avançar", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
                await testRunner.ThenAsync("deve visualizar mensagem informando quantidade mínima inválida", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Informar telefone com mais de 15 caracteres")]
        public async global::System.Threading.Tasks.Task InformarTelefoneComMaisDe15Caracteres()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "15";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Informar telefone com mais de 15 caracteres", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
            this.ScenarioInitialize(scenarioInfo, ruleInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                await testRunner.GivenAsync("que o usuário está no formulário de inscrição", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
                await testRunner.WhenAsync("informa um telefone com mais de 15 caracteres", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
                await testRunner.ThenAsync("o sistema deve impedir a digitação adicional ou exibir validação de limite máximo" +
                        "", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Informar telefone dentro do limite permitido")]
        public async global::System.Threading.Tasks.Task InformarTelefoneDentroDoLimitePermitido()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "16";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Informar telefone dentro do limite permitido", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
            this.ScenarioInitialize(scenarioInfo, ruleInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                await testRunner.GivenAsync("que o usuário está no formulário de inscrição", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
                await testRunner.WhenAsync("informa um telefone entre 10 e 15 caracteres", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
                await testRunner.ThenAsync("o sistema deve aceitar o valor informado", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Informar telefone com letras")]
        public async global::System.Threading.Tasks.Task InformarTelefoneComLetras()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "17";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Informar telefone com letras", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
            this.ScenarioInitialize(scenarioInfo, ruleInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                await testRunner.GivenAsync("que o usuário está no formulário de inscrição", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
                await testRunner.WhenAsync("informa letras no campo Telefone", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
                await testRunner.ThenAsync("deve visualizar mensagem de validação informando que apenas números são permitido" +
                        "s", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Informar telefone com caracteres especiais")]
        public async global::System.Threading.Tasks.Task InformarTelefoneComCaracteresEspeciais()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "18";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Informar telefone com caracteres especiais", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
            this.ScenarioInitialize(scenarioInfo, ruleInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                await testRunner.GivenAsync("que o usuário está no formulário de inscrição", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
                await testRunner.WhenAsync("informa caracteres especiais no campo Telefone", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
                await testRunner.ThenAsync("deve visualizar mensagem de validação informando que apenas números são permitido" +
                        "s", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Informar telefone contendo números e letras")]
        public async global::System.Threading.Tasks.Task InformarTelefoneContendoNumerosELetras()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "19";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Informar telefone contendo números e letras", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
            this.ScenarioInitialize(scenarioInfo, ruleInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                await testRunner.GivenAsync("que o usuário está no formulário de inscrição", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
                await testRunner.WhenAsync("informa números e letras no campo Telefone", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
                await testRunner.ThenAsync("deve visualizar mensagem de validação no campo Telefone", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Informar telefone apenas com números")]
        public async global::System.Threading.Tasks.Task InformarTelefoneApenasComNumeros()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "20";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Informar telefone apenas com números", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
            this.ScenarioInitialize(scenarioInfo, ruleInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                await testRunner.GivenAsync("que o usuário está no formulário de inscrição", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
                await testRunner.WhenAsync("informa um telefone contendo apenas números", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
                await testRunner.ThenAsync("o sistema deve aceitar o valor informado", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Informar CEP com menos de 8 números")]
        public async global::System.Threading.Tasks.Task InformarCEPComMenosDe8Numeros()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "21";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Informar CEP com menos de 8 números", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
            this.ScenarioInitialize(scenarioInfo, ruleInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                await testRunner.GivenAsync("que o usuário está no formulário de inscrição", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
                await testRunner.WhenAsync("informa um CEP com menos de 8 números", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
                await testRunner.AndAsync("tenta avançar", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
                await testRunner.ThenAsync("deve visualizar mensagem de validação de quantidade inválida", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Informar CEP com mais de 8 números")]
        public async global::System.Threading.Tasks.Task InformarCEPComMaisDe8Numeros()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "22";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Informar CEP com mais de 8 números", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
            this.ScenarioInitialize(scenarioInfo, ruleInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                await testRunner.GivenAsync("que o usuário está no formulário de inscrição", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
                await testRunner.WhenAsync("informa um CEP com mais de 8 números", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
                await testRunner.ThenAsync("o sistema deve impedir a digitação adicional ou exibir validação de limite máximo" +
                        "", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Informar CEP com exatamente 8 números")]
        public async global::System.Threading.Tasks.Task InformarCEPComExatamente8Numeros()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "23";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Informar CEP com exatamente 8 números", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
            this.ScenarioInitialize(scenarioInfo, ruleInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                await testRunner.GivenAsync("que o usuário está no formulário de inscrição", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
                await testRunner.WhenAsync("informa um CEP com 8 números", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
                await testRunner.ThenAsync("o sistema deve aceitar o valor informado", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Informar CEP com caracteres não numéricos")]
        public async global::System.Threading.Tasks.Task InformarCEPComCaracteresNaoNumericos()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "24";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Informar CEP com caracteres não numéricos", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
            this.ScenarioInitialize(scenarioInfo, ruleInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                await testRunner.GivenAsync("que o usuário está no formulário de inscrição", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
                await testRunner.WhenAsync("informa letras ou caracteres especiais no campo CEP", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
                await testRunner.ThenAsync("deve visualizar mensagem de validação informando que apenas números são permitido" +
                        "s", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Informar data de nascimento exatamente em 1880")]
        public async global::System.Threading.Tasks.Task InformarDataDeNascimentoExatamenteEm1880()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "25";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Informar data de nascimento exatamente em 1880", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
            this.ScenarioInitialize(scenarioInfo, ruleInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                await testRunner.GivenAsync("que o usuário está no formulário de inscrição", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
                await testRunner.WhenAsync("informa uma data de nascimento no ano de 1880", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
                await testRunner.ThenAsync("o sistema deve aceitar a data informada", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Selecionar data inválida pelo calendário")]
        public async global::System.Threading.Tasks.Task SelecionarDataInvalidaPeloCalendario()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "26";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Selecionar data inválida pelo calendário", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
            this.ScenarioInitialize(scenarioInfo, ruleInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                await testRunner.GivenAsync("que o usuário está no formulário de inscrição", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
                await testRunner.WhenAsync("tenta selecionar uma data anterior a 1880 pelo calendário", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
                await testRunner.ThenAsync("o sistema não deve permitir a seleção da data", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Digitar manualmente data anterior a 1880")]
        public async global::System.Threading.Tasks.Task DigitarManualmenteDataAnteriorA1880()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "27";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Digitar manualmente data anterior a 1880", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
            this.ScenarioInitialize(scenarioInfo, ruleInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                await testRunner.GivenAsync("que o usuário está no formulário de inscrição", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
                await testRunner.WhenAsync("digita manualmente uma data anterior a 1880", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
                await testRunner.AndAsync("tenta avançar", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
                await testRunner.ThenAsync("deve visualizar mensagem de validação no campo Data de nascimento", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
