// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace Subscriptions.Tests.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("Preenchimento do formul�rio de inscri��o")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    [global::NUnit.Framework.CategoryAttribute("chrome")]
    [global::NUnit.Framework.CategoryAttribute("edge")]
    [global::NUnit.Framework.CategoryAttribute("firefox")]
    public partial class PreenchimentoDoFormulRioDeInscriOFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "chrome",
                "edge",
                "firefox"};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("pt"), "Features", "Preenchimento do formul�rio de inscri��o", "  Como candidato\r\n  Eu quero preencher meus dados pessoais e de contato\r\n  Para p" +
                "rosseguir com minha inscri��o\r\n\r\n  Cen�rio: Visualizar formul�rio de inscri��o\r\n" +
                "    Dado que o usu�rio avan�ou ap�s selecionar um curso\r\n    Ent�o deve visualiz" +
                "ar a se��o \"Dados pessoais\"\r\n    E deve visualizar os campos CPF, Nome, Sobrenom" +
                "e e Data de nascimento\r\n    E deve visualizar a se��o \"Contato\"\r\n    E deve visu" +
                "alizar os campos Email, Celular e Telefone\r\n    E deve visualizar a se��o \"Ender" +
                "e�o\"\r\n    E deve visualizar campos de endere�o\r\n    E deve visualizar o bot�o \"V" +
                "oltar\"\r\n    E deve visualizar o bot�o \"Avan�ar\"\r\n    E deve visualizar bot�o Pri" +
                "vacidade\r\n    E deve visualizar bot�o home\r\n    E deve visualizar op��es de tema" +
                "\r\n    E deve visualizar logotipo +a\r\n    E deve visualizar bot�o Portal de inscr" +
                "i��es\r\n\r\n  Cen�rio: Tentar avan�ar com formul�rio vazio\r\n    Dado que o usu�rio " +
                "est� no formul�rio de inscri��o\r\n    Quando clica em \"Avan�ar\" sem preencher os " +
                "campos obrigat�rios\r\n    Ent�o deve visualizar mensagens de valida��o nos campos" +
                " obrigat�rios\r\n\r\n  Cen�rio: Preencher formul�rio com dados v�lidos\r\n    Dado que" +
                " o usu�rio est� no formul�rio de inscri��o\r\n    Quando preenche todos os campos " +
                "obrigat�rios corretamente\r\n    E clica em \"Avan�ar\"\r\n    Ent�o deve avan�ar para" +
                " a pr�xima etapa da inscri��o\r\n\r\n  Cen�rio: Preencher CPF em formato inv�lido\r\n " +
                "   Dado que o usu�rio est� no formul�rio de inscri��o\r\n    Quando informa um CPF" +
                " em formato inv�lido\r\n    Ent�o deve visualizar mensagem de erro no campo CPF\r\n\r" +
                "\n  Cen�rio: Preencher email inv�lido\r\n    Dado que o usu�rio est� no formul�rio " +
                "de inscri��o\r\n    Quando informa um email em formato inv�lido\r\n    Ent�o deve vi" +
                "sualizar mensagem de erro no campo Email\r\n\r\n  Cen�rio: Preencher telefone em for" +
                "mato inv�lido\r\n    Dado que o usu�rio est� no formul�rio de inscri��o\r\n    Quand" +
                "o informa um telefone em formato inv�lido\r\n    Ent�o deve visualizar mensagem de" +
                " erro no campo Telefone\r\n\r\n  Cen�rio: Preencher data de nascimento inv�lida\r\n   " +
                " Dado que o usu�rio est� no formul�rio de inscri��o\r\n    Quando informa uma data" +
                " de nascimento inv�lida\r\n    Ent�o deve visualizar mensagem de erro no campo Dat" +
                "a de nascimento\r\n\r\n  Cen�rio: Preencher CEP em formato inv�lido\r\n    Dado que o " +
                "usu�rio est� no formul�rio de inscri��o\r\n    Quando informa um CEP em formato in" +
                "v�lido\r\n    Ent�o deve visualizar mensagem de erro no campo CEP\r\n\r\n  Cen�rio: Ma" +
                "rcar op��o possui defici�ncia\r\n    Dado que o usu�rio est� no formul�rio de insc" +
                "ri��o\r\n    Quando marca a op��o \"Possui alguma defici�ncia?\"\r\n    Ent�o o sistem" +
                "a deve registrar a escolha do usu�rio\r\n\r\n  Cen�rio: Navegar para tela anterior\r\n" +
                "    Dado que o usu�rio est� no formul�rio de inscri��o\r\n    Quando clica no bot�" +
                "o \"Voltar\"\r\n    Ent�o deve retornar para a tela anterior da inscri��o\r\n\r\n  Cen�r" +
                "io: Preencher parcialmente o formul�rio\r\n    Dado que o usu�rio est� no formul�r" +
                "io de inscri��o\r\n    Quando preenche apenas alguns campos obrigat�rios\r\n    E te" +
                "nta avan�ar\r\n    Ent�o deve visualizar quais campos obrigat�rios n�o foram preen" +
                "chidos\r\n\r\n  Cen�rio: Inserir caracteres especiais em campos de texto\r\n    Dado q" +
                "ue o usu�rio est� no formul�rio de inscri��o\r\n    Quando insere caracteres inv�l" +
                "idos em campos de texto\r\n    Ent�o deve visualizar mensagem de valida��o\r\n\r\n  Ce" +
                "n�rio: Informar CPF com mais de 12 caracteres\r\n    Dado que o usu�rio est� no fo" +
                "rmul�rio de inscri��o\r\n    Quando informa um CPF com mais de 12 caracteres\r\n    " +
                "Ent�o o sistema deve impedir a digita��o adicional ou exibir valida��o de limite" +
                " m�ximo\r\n\r\n  Cen�rio: Informar CPF com quantidade m�xima permitida\r\n    Dado que" +
                " o usu�rio est� no formul�rio de inscri��o\r\n    Quando informa um CPF com at� 12" +
                " caracteres\r\n    Ent�o o sistema deve aceitar o valor informado\r\n\r\n  Cen�rio: In" +
                "formar telefone com menos de 10 caracteres\r\n    Dado que o usu�rio est� no formu" +
                "l�rio de inscri��o\r\n    Quando informa um telefone com menos de 10 caracteres\r\n " +
                "   E tenta avan�ar\r\n    Ent�o deve visualizar mensagem informando quantidade m�n" +
                "ima inv�lida\r\n\r\n  Cen�rio: Informar telefone com mais de 15 caracteres\r\n    Dado" +
                " que o usu�rio est� no formul�rio de inscri��o\r\n    Quando informa um telefone c" +
                "om mais de 15 caracteres\r\n    Ent�o o sistema deve impedir a digita��o adicional" +
                " ou exibir valida��o de limite m�ximo\r\n\r\n  Cen�rio: Informar telefone dentro do " +
                "limite permitido\r\n    Dado que o usu�rio est� no formul�rio de inscri��o\r\n    Qu" +
                "ando informa um telefone entre 10 e 15 caracteres\r\n    Ent�o o sistema deve acei" +
                "tar o valor informado\r\n\r\n  Cen�rio: Informar telefone com letras\r\n    Dado que o" +
                " usu�rio est� no formul�rio de inscri��o\r\n    Quando informa letras no campo Tel" +
                "efone\r\n    Ent�o deve visualizar mensagem de valida��o informando que apenas n�m" +
                "eros s�o permitidos\r\n\r\n  Cen�rio: Informar telefone com caracteres especiais\r\n  " +
                "  Dado que o usu�rio est� no formul�rio de inscri��o\r\n    Quando informa caracte" +
                "res especiais no campo Telefone\r\n    Ent�o deve visualizar mensagem de valida��o" +
                " informando que apenas n�meros s�o permitidos\r\n\r\n  Cen�rio: Informar telefone co" +
                "ntendo n�meros e letras\r\n    Dado que o usu�rio est� no formul�rio de inscri��o\r" +
                "\n    Quando informa n�meros e letras no campo Telefone\r\n    Ent�o deve visualiza" +
                "r mensagem de valida��o no campo Telefone\r\n\r\n  Cen�rio: Informar telefone apenas" +
                " com n�meros\r\n    Dado que o usu�rio est� no formul�rio de inscri��o\r\n    Quando" +
                " informa um telefone contendo apenas n�meros\r\n    Ent�o o sistema deve aceitar o" +
                " valor informado\r\n\r\n  Cen�rio: Informar CEP com menos de 8 n�meros\r\n    Dado que" +
                " o usu�rio est� no formul�rio de inscri��o\r\n    Quando informa um CEP com menos " +
                "de 8 n�meros\r\n    E tenta avan�ar\r\n    Ent�o deve visualizar mensagem de valida�" +
                "�o de quantidade inv�lida\r\n\r\n  Cen�rio: Informar CEP com mais de 8 n�meros\r\n    " +
                "Dado que o usu�rio est� no formul�rio de inscri��o\r\n    Quando informa um CEP co" +
                "m mais de 8 n�meros\r\n    Ent�o o sistema deve impedir a digita��o adicional ou e" +
                "xibir valida��o de limite m�ximo\r\n\r\n  Cen�rio: Informar CEP com exatamente 8 n�m" +
                "eros\r\n    Dado que o usu�rio est� no formul�rio de inscri��o\r\n    Quando informa" +
                " um CEP com 8 n�meros\r\n    Ent�o o sistema deve aceitar o valor informado\r\n\r\n  C" +
                "en�rio: Informar CEP com caracteres n�o num�ricos\r\n    Dado que o usu�rio est� n" +
                "o formul�rio de inscri��o\r\n    Quando informa letras ou caracteres especiais no " +
                "campo CEP\r\n    Ent�o deve visualizar mensagem de valida��o informando que apenas" +
                " n�meros s�o permitidos\r\n\r\n  Cen�rio: Informar data de nascimento exatamente em " +
                "1880\r\n    Dado que o usu�rio est� no formul�rio de inscri��o\r\n    Quando informa" +
                " uma data de nascimento no ano de 1880\r\n    Ent�o o sistema deve aceitar a data " +
                "informada\r\n\r\n  Cen�rio: Selecionar data inv�lida pelo calend�rio\r\n    Dado que o" +
                " usu�rio est� no formul�rio de inscri��o\r\n    Quando tenta selecionar uma data a" +
                "nterior a 1880 pelo calend�rio\r\n    Ent�o o sistema n�o deve permitir a sele��o " +
                "da data\r\n\r\n  Cen�rio: Digitar manualmente data anterior a 1880\r\n    Dado que o u" +
                "su�rio est� no formul�rio de inscri��o\r\n    Quando digita manualmente uma data a" +
                "nterior a 1880\r\n    E tenta avan�ar\r\n    Ent�o deve visualizar mensagem de valid" +
                "a��o no campo Data de nascimento", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "Formulario_inscricao.feature"
#line hidden
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Formulario_inscricao.feature.ndjson", 2);
        }
    }
}
#pragma warning restore
#endregion
