// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace Subscriptions.Tests.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("P�gina inicial do portal de inscri��es")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    [global::NUnit.Framework.CategoryAttribute("chrome")]
    [global::NUnit.Framework.CategoryAttribute("edge")]
    [global::NUnit.Framework.CategoryAttribute("firefox")]
    public partial class PGinaInicialDoPortalDeInscriEsFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "chrome",
                "edge",
                "firefox"};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("pt"), "Features", "P�gina inicial do portal de inscri��es", "  Como visitante do portal\r\n  Eu quero visualizar as op��es de ensino\r\n  Para ini" +
                "ciar minha inscri��o\r\n\r\n  Cen�rio: Acessar p�gina inicial\r\n    Dado que o usu�ri" +
                "o acessa o portal de inscri��es\r\n    Ent�o deve visualizar o seletor de n�vel de" +
                " ensino\r\n    E bot�o Privacidade\r\n    E bot�o home\r\n    E op��es de tema\r\n    E " +
                "logotipo +a\r\n    E bot�o Portal de inscri��es\r\n\r\n  Cen�rio: Visualizar n�veis de" +
                " ensino dispon�veis\r\n    Dado que o usu�rio est� na p�gina inicial\r\n    Quando e" +
                "xpande o seletor de n�vel de ensino\r\n    Ent�o deve visualizar a op��o \"Gradua��" +
                "o\"\r\n    E deve visualizar a op��o \"P�s-gradua��o\"\r\n\r\n  Cen�rio: Acessar pol�tica" +
                " de privacidade\r\n    Dado que o usu�rio est� na p�gina inicial\r\n    Quando clica" +
                " em \"Privacidade\"\r\n    Ent�o deve visualizar a p�gina de privacidade\r\n\r\n  Cen�ri" +
                "o: Alterar para tema escuro\r\n    Dado que o usu�rio est� na p�gina inicial\r\n    " +
                "Quando seleciona o tema \"Escuro\"\r\n    Ent�o a interface deve ser exibida em modo" +
                " escuro\r\n\r\n  Cen�rio: Alterar para tema claro\r\n    Dado que o usu�rio est� na p�" +
                "gina inicial\r\n    Quando seleciona o tema \"Claro\"\r\n    Ent�o a interface deve se" +
                "r exibida em modo claro\r\n\r\n  Cen�rio: Alterar para tema do sistema\r\n    Dado que" +
                " o usu�rio est� na p�gina inicial\r\n    Quando seleciona o tema \"Sistema\"\r\n    En" +
                "t�o a interface deve seguir o tema do sistema operacional\r\n\r\n  Cen�rio: Selecion" +
                "ar n�vel Gradua��o\r\n    Dado que o usu�rio est� na p�gina inicial\r\n    Quando ex" +
                "pande o seletor de n�vel de ensino\r\n    E seleciona o n�vel \"Gradua��o\"\r\n    Ent" +
                "�o deve avan�ar para o fluxo de inscri��o de Gradua��o\r\n\r\n  Cen�rio: Selecionar " +
                "n�vel P�s-gradua��o\r\n    Dado que o usu�rio est� na p�gina inicial\r\n    Quando e" +
                "xpande o seletor de n�vel de ensino\r\n    E seleciona o n�vel \"P�s-gradua��o\"\r\n  " +
                "  Ent�o deve avan�ar para o fluxo de inscri��o de P�s-gradua��o", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "Home.feature"
#line hidden
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Home.feature.ndjson", 2);
        }
    }
}
#pragma warning restore
#endregion
