// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace Subscriptions.Tests.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("Página inicial do portal de inscrições")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    [global::NUnit.Framework.CategoryAttribute("chrome")]
    [global::NUnit.Framework.CategoryAttribute("edge")]
    [global::NUnit.Framework.CategoryAttribute("firefox")]
    public partial class PaginaInicialDoPortalDeInscricoesFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "chrome",
                "edge",
                "firefox"};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("pt"), "Features", "Página inicial do portal de inscrições", "  Como visitante do portal\r\n  Eu quero visualizar as opções de ensino\r\n  Para ini" +
                "ciar minha inscrição", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Home.feature.ndjson", 10);
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Acessar página inicial")]
        public async global::System.Threading.Tasks.Task AcessarPaginaInicial()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Acessar página inicial", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
            this.ScenarioInitialize(scenarioInfo, ruleInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                await testRunner.GivenAsync("que o usuário acessa o portal de inscrições", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
                await testRunner.ThenAsync("deve visualizar o seletor de nível de ensino", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
                await testRunner.AndAsync("botão Privacidade", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
                await testRunner.AndAsync("botão home", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
                await testRunner.AndAsync("opções de tema", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
                await testRunner.AndAsync("logotipo +a", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
                await testRunner.AndAsync("botão Portal de inscrições", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Visualizar níveis de ensino disponíveis")]
        public async global::System.Threading.Tasks.Task VisualizarNiveisDeEnsinoDisponiveis()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Visualizar níveis de ensino disponíveis", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
            this.ScenarioInitialize(scenarioInfo, ruleInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                await testRunner.GivenAsync("que o usuário está na página inicial", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
                await testRunner.WhenAsync("expande o seletor de nível de ensino", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
                await testRunner.ThenAsync("deve visualizar a opção \"Graduação\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
                await testRunner.AndAsync("deve visualizar a opção \"Pós-graduação\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Acessar política de privacidade")]
        public async global::System.Threading.Tasks.Task AcessarPoliticaDePrivacidade()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Acessar política de privacidade", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
            this.ScenarioInitialize(scenarioInfo, ruleInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                await testRunner.GivenAsync("que o usuário está na página inicial", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
                await testRunner.WhenAsync("clica em \"Privacidade\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
                await testRunner.ThenAsync("deve visualizar a página de privacidade", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Alterar para tema escuro")]
        public async global::System.Threading.Tasks.Task AlterarParaTemaEscuro()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Alterar para tema escuro", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
            this.ScenarioInitialize(scenarioInfo, ruleInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                await testRunner.GivenAsync("que o usuário está na página inicial", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
                await testRunner.WhenAsync("seleciona o tema \"Escuro\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
                await testRunner.ThenAsync("a interface deve ser exibida em modo escuro", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Alterar para tema claro")]
        public async global::System.Threading.Tasks.Task AlterarParaTemaClaro()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Alterar para tema claro", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
            this.ScenarioInitialize(scenarioInfo, ruleInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                await testRunner.GivenAsync("que o usuário está na página inicial", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
                await testRunner.WhenAsync("seleciona o tema \"Claro\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
                await testRunner.ThenAsync("a interface deve ser exibida em modo claro", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Alterar para tema do sistema")]
        public async global::System.Threading.Tasks.Task AlterarParaTemaDoSistema()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Alterar para tema do sistema", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
            this.ScenarioInitialize(scenarioInfo, ruleInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                await testRunner.GivenAsync("que o usuário está na página inicial", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
                await testRunner.WhenAsync("seleciona o tema \"Sistema\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
                await testRunner.ThenAsync("a interface deve seguir o tema do sistema operacional", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Selecionar nível Graduação")]
        public async global::System.Threading.Tasks.Task SelecionarNivelGraduacao()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "6";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Selecionar nível Graduação", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
            this.ScenarioInitialize(scenarioInfo, ruleInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                await testRunner.GivenAsync("que o usuário está na página inicial", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
                await testRunner.WhenAsync("expande o seletor de nível de ensino", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
                await testRunner.AndAsync("seleciona o nível \"Graduação\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
                await testRunner.ThenAsync("deve avançar para o fluxo de inscrição de Graduação", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Selecionar nível Pós-graduação")]
        public async global::System.Threading.Tasks.Task SelecionarNivelPos_Graduacao()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "7";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Selecionar nível Pós-graduação", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
            this.ScenarioInitialize(scenarioInfo, ruleInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                await testRunner.GivenAsync("que o usuário está na página inicial", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
                await testRunner.WhenAsync("expande o seletor de nível de ensino", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
                await testRunner.AndAsync("seleciona o nível \"Pós-graduação\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
                await testRunner.ThenAsync("deve avançar para o fluxo de inscrição de Pós-graduação", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
