// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace Subscriptions.Tests.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("Sele��o de curso de Gradua��o")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    [global::NUnit.Framework.CategoryAttribute("chrome")]
    [global::NUnit.Framework.CategoryAttribute("edge")]
    [global::NUnit.Framework.CategoryAttribute("firefox")]
    public partial class SeleODeCursoDeGraduaOFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "chrome",
                "edge",
                "firefox"};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("pt"), "Features", "Sele��o de curso de Gradua��o", "  Como usu�rio do portal de inscri��es\r\n  Eu quero selecionar um curso de Gradua�" +
                "�o\r\n  Para continuar minha inscri��o\r\n\r\n  Cen�rio: Visualizar tela de sele��o de" +
                " curso de Gradua��o\r\n    Dado que o usu�rio selecionou o n�vel \"Gradua��o\"\r\n    " +
                "Ent�o deve visualizar o t�tulo \"Selecione seu curso de Gradua��o\"\r\n    E deve vi" +
                "sualizar o seletor de cursos\r\n    E deve visualizar o bot�o \"Voltar\"\r\n    E deve" +
                " visualizar o bot�o \"Avan�ar\"\r\n    E deve visualizar bot�o Privacidade\r\n    E de" +
                "ve visualizar bot�o home\r\n    E deve visualizar op��es de tema\r\n    E deve visua" +
                "lizar logotipo +a\r\n    E deve visualizar bot�o Portal de inscri��es\r\n\r\n  Cen�rio" +
                ": Visualizar op��es de cursos dispon�veis\r\n    Dado que o usu�rio est� na tela d" +
                "e sele��o de curso de Gradua��o\r\n    Quando expande o seletor de cursos\r\n    Ent" +
                "�o deve visualizar a lista de cursos dispon�veis\r\n\r\n  Cen�rio: Avan�ar sem selec" +
                "ionar curso\r\n    Dado que o usu�rio est� na tela de sele��o de curso de Gradua��" +
                "o\r\n    Quando clica no bot�o \"Avan�ar\"\r\n    Ent�o n�o deve avan�ar para o pr�xim" +
                "o passo\r\n\r\n  Cen�rio: Selecionar curso e avan�ar\r\n    Dado que o usu�rio est� na" +
                " tela de sele��o de curso de Gradua��o\r\n    Quando seleciona um curso\r\n    E cli" +
                "ca no bot�o \"Avan�ar\"\r\n    Ent�o deve avan�ar para a pr�xima etapa da inscri��o\r" +
                "\n\r\n  Cen�rio: Voltar para sele��o de n�vel\r\n    Dado que o usu�rio est� na tela " +
                "de sele��o de curso de Gradua��o\r\n    Quando clica no bot�o \"Voltar\"\r\n    Ent�o " +
                "deve retornar para a sele��o de n�vel de ensino\r\n\r\n  Cen�rio: Exibir mensagem ao" +
                " tentar avan�ar sem selecionar curso\r\n    Dado que o usu�rio est� na tela de sel" +
                "e��o de curso de Gradua��o\r\n    Quando clica no bot�o \"Avan�ar\" sem selecionar u" +
                "m curso\r\n    Ent�o deve visualizar uma mensagem informando que � necess�rio sele" +
                "cionar um curso\r\n\r\n  Cen�rio: Selecionar curso v�lido\r\n    Dado que o usu�rio es" +
                "t� na tela de sele��o de curso de Gradua��o\r\n    Quando seleciona um curso v�lid" +
                "o\r\n    Ent�o o curso selecionado deve ser exibido no seletor\r\n\r\n  Cen�rio: Pesqu" +
                "isar curso existente\r\n    Dado que o usu�rio est� na tela de sele��o de curso de" +
                " Gradua��o\r\n    Quando digita o nome de um curso existente no campo de pesquisa\r" +
                "\n    Ent�o deve visualizar cursos correspondentes ao termo pesquisado\r\n\r\n  Cen�r" +
                "io: Pesquisar curso inexistente\r\n    Dado que o usu�rio est� na tela de sele��o " +
                "de curso de Gradua��o\r\n    Quando digita um curso inexistente no campo de pesqui" +
                "sa\r\n    Ent�o n�o deve visualizar resultados na lista\r\n\r\n  Cen�rio: Limpar campo" +
                " de pesquisa\r\n    Dado que o usu�rio realizou uma busca por curso\r\n    Quando li" +
                "mpa o campo de pesquisa\r\n    Ent�o deve visualizar novamente todos os cursos dis" +
                "pon�veis", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "Selecao_curso_graduacao.feature"
#line hidden
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Selecao_curso_graduacao.feature.ndjson", 2);
        }
    }
}
#pragma warning restore
#endregion
