// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace Subscriptions.Tests.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("Seleção de curso de Graduação")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    [global::NUnit.Framework.CategoryAttribute("chrome")]
    [global::NUnit.Framework.CategoryAttribute("edge")]
    [global::NUnit.Framework.CategoryAttribute("firefox")]
    public partial class SelecaoDeCursoDeGraduacaoFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "chrome",
                "edge",
                "firefox"};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("pt"), "Features", "Seleção de curso de Graduação", "  Como usuário do portal de inscrições\r\n  Eu quero selecionar um curso de Graduaç" +
                "ão\r\n  Para continuar minha inscrição", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Selecao_curso_graduacao.feature.ndjson", 12);
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Visualizar tela de seleção de curso de Graduação")]
        public async global::System.Threading.Tasks.Task VisualizarTelaDeSelecaoDeCursoDeGraduacao()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Visualizar tela de seleção de curso de Graduação", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
            this.ScenarioInitialize(scenarioInfo, ruleInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                await testRunner.GivenAsync("que o usuário selecionou o nível \"Graduação\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
                await testRunner.ThenAsync("deve visualizar o título \"Selecione seu curso de Graduação\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
                await testRunner.AndAsync("deve visualizar o seletor de cursos", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
                await testRunner.AndAsync("deve visualizar o botão \"Voltar\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
                await testRunner.AndAsync("deve visualizar o botão \"Avançar\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
                await testRunner.AndAsync("deve visualizar botão Privacidade", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
                await testRunner.AndAsync("deve visualizar botão home", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
                await testRunner.AndAsync("deve visualizar opções de tema", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
                await testRunner.AndAsync("deve visualizar logotipo +a", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
                await testRunner.AndAsync("deve visualizar botão Portal de inscrições", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Visualizar opções de cursos disponíveis")]
        public async global::System.Threading.Tasks.Task VisualizarOpcoesDeCursosDisponiveis()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Visualizar opções de cursos disponíveis", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
            this.ScenarioInitialize(scenarioInfo, ruleInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                await testRunner.GivenAsync("que o usuário está na tela de seleção de curso de Graduação", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
                await testRunner.WhenAsync("expande o seletor de cursos", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
                await testRunner.ThenAsync("deve visualizar a lista de cursos disponíveis", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Avançar sem selecionar curso")]
        public async global::System.Threading.Tasks.Task AvancarSemSelecionarCurso()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Avançar sem selecionar curso", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
            this.ScenarioInitialize(scenarioInfo, ruleInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                await testRunner.GivenAsync("que o usuário está na tela de seleção de curso de Graduação", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
                await testRunner.WhenAsync("clica no botão \"Avançar\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
                await testRunner.ThenAsync("não deve avançar para o próximo passo", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Selecionar curso e avançar")]
        public async global::System.Threading.Tasks.Task SelecionarCursoEAvancar()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Selecionar curso e avançar", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
            this.ScenarioInitialize(scenarioInfo, ruleInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                await testRunner.GivenAsync("que o usuário está na tela de seleção de curso de Graduação", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
                await testRunner.WhenAsync("seleciona um curso", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
                await testRunner.AndAsync("clica no botão \"Avançar\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
                await testRunner.ThenAsync("deve avançar para a próxima etapa da inscrição", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Voltar para seleção de nível")]
        public async global::System.Threading.Tasks.Task VoltarParaSelecaoDeNivel()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Voltar para seleção de nível", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
            this.ScenarioInitialize(scenarioInfo, ruleInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                await testRunner.GivenAsync("que o usuário está na tela de seleção de curso de Graduação", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
                await testRunner.WhenAsync("clica no botão \"Voltar\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
                await testRunner.ThenAsync("deve retornar para a seleção de nível de ensino", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Exibir mensagem ao tentar avançar sem selecionar curso")]
        public async global::System.Threading.Tasks.Task ExibirMensagemAoTentarAvancarSemSelecionarCurso()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Exibir mensagem ao tentar avançar sem selecionar curso", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
            this.ScenarioInitialize(scenarioInfo, ruleInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                await testRunner.GivenAsync("que o usuário está na tela de seleção de curso de Graduação", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
                await testRunner.WhenAsync("clica no botão \"Avançar\" sem selecionar um curso", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
                await testRunner.ThenAsync("deve visualizar uma mensagem informando que é necessário selecionar um curso", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Selecionar curso válido")]
        public async global::System.Threading.Tasks.Task SelecionarCursoValido()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "6";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Selecionar curso válido", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
            this.ScenarioInitialize(scenarioInfo, ruleInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                await testRunner.GivenAsync("que o usuário está na tela de seleção de curso de Graduação", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
                await testRunner.WhenAsync("seleciona um curso válido", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
                await testRunner.ThenAsync("o curso selecionado deve ser exibido no seletor", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Pesquisar curso existente")]
        public async global::System.Threading.Tasks.Task PesquisarCursoExistente()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "7";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Pesquisar curso existente", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
            this.ScenarioInitialize(scenarioInfo, ruleInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                await testRunner.GivenAsync("que o usuário está na tela de seleção de curso de Graduação", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
                await testRunner.WhenAsync("digita o nome de um curso existente no campo de pesquisa", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
                await testRunner.ThenAsync("deve visualizar cursos correspondentes ao termo pesquisado", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Pesquisar curso inexistente")]
        public async global::System.Threading.Tasks.Task PesquisarCursoInexistente()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "8";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Pesquisar curso inexistente", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
            this.ScenarioInitialize(scenarioInfo, ruleInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                await testRunner.GivenAsync("que o usuário está na tela de seleção de curso de Graduação", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
                await testRunner.WhenAsync("digita um curso inexistente no campo de pesquisa", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
                await testRunner.ThenAsync("não deve visualizar resultados na lista", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Limpar campo de pesquisa")]
        public async global::System.Threading.Tasks.Task LimparCampoDePesquisa()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "9";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Limpar campo de pesquisa", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
            this.ScenarioInitialize(scenarioInfo, ruleInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                await testRunner.GivenAsync("que o usuário realizou uma busca por curso", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
                await testRunner.WhenAsync("limpa o campo de pesquisa", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
                await testRunner.ThenAsync("deve visualizar novamente todos os cursos disponíveis", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
